# Generated by Django 3.0.6 on 2020-06-26 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interestpage', '0002_auto_20200618_1606'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Interest',
        ),
    ]
